imports:
#    - { resource: "@AdminBundle/Resources/config/security.yml" }
#    - { resource: "@AdminBundle/Resources/config/services.yml" }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: ArmandoProject\AdminBundle\Entity\User
    registration:
        form:
          type: ArmandoProject\AdminBundle\Form\RegistrationType
          name: admin_user_registration
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

vich_uploader:
    db_driver: orm
    mappings:
        product_image:
          uri_prefix: /profiles/images
          upload_destination: '%kernel.root_dir%/../web/profiles/images'
          delete_on_remove:   true
