<?php

namespace ArmandoProject\AdminBundle\Repository;

/**
 * fileUploaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fileUploaderRepository extends \Doctrine\ORM\EntityRepository
{
}
